dm_forum_index:
    path:     /
    defaults:
        _controller:    DMForumBundle:Forum:index

dm_forum_test:
    path:     /test/{value}
    defaults:
        _controller:    DMForumBundle:Forum:test
        
dm_forum_testhydrate:
    path:     /hydrate/{author}/{message}
    defaults:
        _controller:    DMForumBundle:Forum:testHydrate

dm_forum_viewMess:
    path:     /view
    defaults:
        _controller:    DMForumBundle:Forum:view

dm_forum_viewByAuthor:
    path:     /viewByAuthor/{author}
    defaults:
        _controller:    DMForumBundle:Forum:viewByAuthor

dm_forum_formulaire:
    path:     /form
    defaults:
        _controller:    DMForumBundle:Forum:form
        
dm_forum_formSucces:
    path:     /formSucces
    defaults:
        _controller:    DMForumBundle:Forum:formSucces